# -*- coding: utf-8 -*-
"""streamlit_git_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJthToNTbRYRwFrYnjYjNwfnWMsPEp8v
"""

# -*- coding: utf-8 -*-
"""Streamlit app to explore US Corn Belt yield data over time.
"""

# Libraries
import pandas as pd
import geopandas as gpd
import streamlit as st
import pydeck as pdk
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge, Lasso, ElasticNet

# Preprocessing
@st.cache_data
@st.cache_data
def preprocess_data(file_path_avg, file_path_cv, shapefile_path):
    # Load both CSVs
    avg_df = pd.read_csv(file_path_avg)
    cv_df = pd.read_csv(file_path_cv)

    shp_gdf = gpd.read_file(shapefile_path)

    # Merge both CSVs with shapefile
    merged_avg = shp_gdf.merge(avg_df, left_on='ID_2', right_on='id2')
    merged_cv = shp_gdf.merge(cv_df, left_on='ID_2', right_on='id2')

    # Simplify geometry
    merged_avg['geometry'] = merged_avg['geometry'].simplify(0.01)
    merged_cv['geometry'] = merged_cv['geometry'].simplify(0.01)

    years = sorted(avg_df['year'].unique())

    return merged_avg, merged_cv, years


from PIL import Image

def make_colorbar():
    # Horizontal gradient: Blue → Purple → Red
    width, height = 256, 20
    colorbar = Image.new("RGBA", (width, height))
    for x in range(width):
        r = int(255 * (x / (width - 1)))
        g = 120
        b = int(255 * (1 - x / (width - 1)))
        for y in range(height):
            colorbar.putpixel((x, y), (r, g, b, 255))
    return colorbar

# Computation of density function - for plot
def kde_1d(data, num_points=200, bandwidth=None):
    data = np.asarray(data)
    data = data[~np.isnan(data)]

    # Silverman's rule of thumb if no bandwidth provided
    if bandwidth is None:
        bandwidth = 1.06 * data.std() * len(data) ** (-1/5)

    xs = np.linspace(data.min(), data.max(), num_points)
    density = np.zeros_like(xs)

    for x in data:
        density += np.exp(-0.5 * ((xs - x) / bandwidth) ** 2)

    density /= (len(data) * bandwidth * np.sqrt(2 * np.pi))
    return xs, density

def ale_1d(model, X: pd.DataFrame, feature: str, n_bins: int = 20):
    """
    1D Accumulated Local Effects (ALE) for a fitted sklearn model.
    Works with Pipelines (imputer/scaler/reg) because we call model.predict on full X.

    Returns a dataframe with columns: ['x', 'ale'] where x is bin center.
    """
    X = X.copy()

    # Feature values (may contain NaNs)
    x = X[feature].astype(float)

    # Use quantile bins on observed (non-null) values
    x_nonnull = x.dropna()
    if x_nonnull.nunique() < 2:
        # Not enough variation
        return pd.DataFrame({"x": [], "ale": []})

    # Bin edges (quantiles); unique to avoid zero-width bins
    edges = np.quantile(x_nonnull, np.linspace(0, 1, n_bins + 1))
    edges = np.unique(edges)
    if len(edges) < 3:
        return pd.DataFrame({"x": [], "ale": []})

    # Assign each row to a bin (only for non-null rows)
    bins = pd.cut(x, bins=edges, include_lowest=True, labels=False)

    # For each bin k, compute avg local effect:
    # E[ f(x_upper, x_-j) - f(x_lower, x_-j) | x in bin k ]
    local_effects = []
    centers = []

    for k in range(len(edges) - 1):
        idx = bins == k
        if idx.sum() == 0:
            local_effects.append(0.0)
            centers.append((edges[k] + edges[k + 1]) / 2)
            continue

        X_low = X.loc[idx].copy()
        X_high = X.loc[idx].copy()

        X_low[feature] = edges[k]
        X_high[feature] = edges[k + 1]

        pred_high = model.predict(X_high)
        pred_low = model.predict(X_low)

        local_effect = float(np.mean(pred_high - pred_low))
        local_effects.append(local_effect)
        centers.append((edges[k] + edges[k + 1]) / 2)

    # Accumulate and center (ALE is defined up to a constant; center to mean 0)
    ale_vals = np.cumsum(local_effects)
    ale_vals = ale_vals - np.mean(ale_vals)

    return pd.DataFrame({"x": centers, "ale": ale_vals})


def make_model_pipeline(model_choice, alpha, l1_ratio=None):
    if model_choice == "Ridge":
        reg = Ridge(alpha=alpha)
    elif model_choice == "Lasso":
        reg = Lasso(alpha=alpha)
    else:
        reg = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)

    return Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("reg", reg),
    ])

FEATURE_UNITS = {
    "yield": "bu/acre",
    "tmmx": "K", 
    "tmmn": "K",
    "rmax": "%", 
    "rmin": "%", 
    "sph": "g/kg",
    "vpd": "kPa",
    "pr": "kg/m²",
    "srad": "W/m²",
    "vs": "m/s",
    "th": "°"
}

def add_climate_stress_metric(
    gdf,
    year,
    temp_col="tmmx",
    pr_col="pr",
    heat_power=2.0,
    dry_power=2.0,
    heat_weight=0.5,
):
    """
    Creates a continuous climate stress index in [0,1] for a given year.
    Higher = worse. Increases with higher temperature and lower precipitation.

    stress_raw = heat_weight*(temp_norm**heat_power) + (1-heat_weight)*(dry_norm**dry_power)
    where:
      temp_norm in [0,1] is higher when temp is higher
      dry_norm  in [0,1] is higher when precip is lower (i.e., dryness)
    """
    gdf_year = gdf[gdf["year"] == year].copy()

    # Pull series
    t = gdf_year[temp_col].astype(float)
    p = gdf_year[pr_col].astype(float)

    # Normalize temp: higher temp -> closer to 1
    t_min, t_max = np.nanmin(t), np.nanmax(t)
    temp_norm = (t - t_min) / (t_max - t_min + 1e-9)

    # Normalize precip: higher precip -> closer to 1, then invert to get dryness
    p_min, p_max = np.nanmin(p), np.nanmax(p)
    pr_norm = (p - p_min) / (p_max - p_min + 1e-9)
    dry_norm = 1.0 - pr_norm  # higher when precip is lower

    # Optional nonlinear amplification (defaults are already nonlinear with power=2)
    heat_term = np.power(np.clip(temp_norm, 0, 1), heat_power)
    dry_term  = np.power(np.clip(dry_norm, 0, 1),  dry_power)

    stress = heat_weight * heat_term + (1 - heat_weight) * dry_term

    gdf_year["climate_stress"] = stress
    # for tooltip display
    gdf_year["climate_stress_disp"] = (gdf_year["climate_stress"] * 100).round(2)

    return gdf_year



# Choropleth plotting function
def plot_choropleth(gdf, feature, year):
    # Filter for selected year
    gdf_year = gdf[gdf['year'] == year].copy()

    # Feature-specific scaling (important)
    min_val = gdf_year[feature].min()
    max_val = gdf_year[feature].max()

    gdf_year["__norm"] = (gdf_year[feature] - min_val) / (max_val - min_val + 1e-9)
    gdf_year["color"] = gdf_year["__norm"].apply(lambda x: [int(255 * x), 120, int(255 * (1 - x)), 180])

    gdf_year["value_disp"] = gdf_year[feature].round(4)
    
    layer = pdk.Layer(
        "GeoJsonLayer",
        gdf_year,
        opacity=0.75,
        stroked=True,
        filled=True,
        get_fill_color="color",
        get_line_color=[0, 0, 0],
        pickable=True,
    )

    view_state = pdk.ViewState(
        latitude=40.0,
        longitude=-93.0,
        zoom=4,
        pitch=0,
    )
    r = pdk.Deck(
        layers=[layer],
        initial_view_state=view_state,
        tooltip={
            "html": "<b>{NAME_2}</b><br>" + feature + ": {value_disp}",
            "style": {"backgroundColor": "white", "color": "black"}
        },
)


    # Layout: map left, scale right
    left, right = st.columns([4, 1])

    with left:
        st.pydeck_chart(r)
        st.caption(f"Showing **{feature}** for **{year}**")

        # Show horizontal gradient
        st.image(make_colorbar(), use_column_width=True)
        
        # Get units (default: "")
        unit = FEATURE_UNITS.get(feature, "")
        
        # Build formatted labels
        min_label = f"{min_val:.4f} {unit}"
        max_label = f"{max_val:.4f} {unit}"
        
        # Show left/right labels under the colorbar
        cols = st.columns([1, 1])
        cols[0].markdown(f"**{min_label}**")
        cols[1].markdown(f"<div style='text-align:right'><b>{max_label}</b></div>", unsafe_allow_html=True)


    # Display key statistics
    with right:
        st.write("### Values")
        st.metric("Minimum", f"{min_val:.4f}")
        st.metric("Maximum", f"{max_val:.4f}")
        st.metric("Mean", f"{gdf_year[feature].mean():.4f}")
        st.metric("Median", f"{gdf_year[feature].median():.4f}")

    st.write(f"### Distribution of {feature} in {year}")
    
    vals = gdf_year[feature].dropna()
    xs, density = kde_1d(vals)
    
    density_df = pd.DataFrame({"value": xs, "density": density})
    density_df = density_df.set_index("value") 

    # Display density plot
    st.area_chart(density_df)





# Streamlit App
def main():
    st.set_page_config(layout="wide")
    st.title("US Corn Belt Yield Dashboard")

    st.text("Welcome to the dashboard!")
    st.text("Select 'Explore' to view the feature and yield values county by county, 'Climate Stress' to gauge how dryness and heat impact regions, or 'Model Builder' to build your own regression model!")

    file_path_avg = "all_feature_data_avg.csv"
    file_path_cv = "all_feature_data_coeff_of_variation.csv"
    shapefile_path = "CornBeltCounty.shp"

    # Load data
    merged_avg, merged_cv, years = preprocess_data(file_path_avg, file_path_cv, shapefile_path)

    # Sidebar: select active tab
    # active_tab = st.sidebar.radio("Select App Section", ["Exploration", "Model Builder"])
    tab1, tab_stress, tab2, tab3 = st.tabs(["Exploration", "Climate Stress", "Model Builder", "Data Dictionary"])

    # Exploration Sidebar Controls
    # Tabs

    # Tab 1: Exploration
    with tab1:
        st.header("Exploration Controls")
        col1, col2 = st.columns([1,2])
        with col1:
            dataset_choice = st.selectbox(
                "Dataset Type",
                ["Mean", "Coefficient of Variation"]
            )

            if dataset_choice == "Mean":
                active_gdf = merged_avg
            else:
                active_gdf = merged_cv

            year = st.slider(
                "Select Year",
                min_value=min(years),
                max_value=max(years),
                value=max(years)
            )

            cols_to_use = [
                'yield', 'tmmx', 'rmax', 'vs', 'sph', 'srad',
                'vpd', 'rmin', 'pr', 'tmmn', 'th'
            ]
            feature = st.selectbox("Select Feature", cols_to_use, index=0)
        st.divider()

        tab1.header(f"{dataset_choice}: {feature.title()} Map - {year}")
            # st.header(f"{dataset_choice}: {feature.title()} Map - {year}")
        plot_choropleth(active_gdf, feature, year)
        # else:
            # st.info("Switch to Exploration tab to see observed data.")

    # Climate Stress
    with tab_stress:
        st.header("Climate Stress Controls")
        st.write(
            "Climate stress is a continuous index (higher = worse) that increases with **higher temperature** "
            "and **lower precipitation**. Exponents control severity, and weight controls importance."
        )

        col1, col2 = st.columns([1, 2])

        with col1:
            # Choose year
            stress_year = st.slider(
                "Select Year",
                min_value=min(years),
                max_value=max(years),
                value=max(years),
                key="stress_year_slider",
            )

            # Nonlinearity controls
            heat_power = st.slider(
                "Heat nonlinearity (power on normalized temperature)",
                min_value=0.5,
                max_value=5.0,
                value=2.0,
                step=0.1,
            )

            dry_power = st.slider(
                "Dryness nonlinearity (power on normalized dryness)",
                min_value=0.5,
                max_value=5.0,
                value=2.0,
                step=0.1,
            )

            heat_weight = st.slider(
                "Weight on heat vs dryness (0 = all dryness, 1 = all heat)",
                min_value=0.0,
                max_value=1.0,
                value=0.5,
                step=0.05,
            )

        st.divider()

        # Build stress-year GDF (use mean dataset for interpretability)
        stress_gdf_year = add_climate_stress_metric(
            merged_avg,
            year=stress_year,
            temp_col="tmmx",
            pr_col="pr",
            heat_power=heat_power,
            dry_power=dry_power,
            heat_weight=heat_weight,
        )

        # Reuse your choropleth function by plotting the computed column
        st.header(f"Climate Stress Map – {stress_year}")
        plot_choropleth(stress_gdf_year, "climate_stress", stress_year)

        st.caption("Tip: If you increase the powers above 1, counties in the hottest/driest tail will stand out much more.")

    
    # Tab 2: Model Builder
    with tab2:
        st.header("Model Builder Controls")

        # Predictor features (exclude 'yield')
        predictor_features = [
            'tmmx', 'rmax', 'vs', 'sph', 'srad',
            'vpd', 'rmin', 'pr', 'tmmn', 'th'
        ]

        col1, col2 = st.columns([1,2])
        with col1:
            model_features = st.multiselect(
                "Select Features for Regression:",
                predictor_features,
                default=['tmmx', 'rmax', 'pr']
            )
            
            model_choice = st.selectbox(
                "Select Model Type:",
                ["Ridge", "Lasso", "Elastic Net"]
            )
    
            # Hyperparameters
            alpha = st.number_input(
                "Alpha (regularization strength)",
                min_value=0.0,
                value=1.0,     # default
                step=0.1,
                format="%.4f"
            )

            # Only show l1_ratio slider if Elastic Net is selected
            if model_choice == "Elastic Net":
                l1_ratio = st.number_input(
                    "L1 Ratio (Elastic Net only)",
                    min_value=0.0,
                    max_value=1.0,
                    value=0.5,      # default
                    step=0.05,
                    format="%.2f"
                )
            else:
                l1_ratio = None

            pred_year = st.selectbox(
                "Select Year to Visualize Predictions:",
                years,
                index=len(years)-1
            )

        st.divider()

        if len(model_features) == 0:
            st.sidebar.warning("Please select at least one feature.")
            st.stop()
        # if active_tab != "Model Builder":
            # st.info("Switch to Model Builder tab to run the model.")
            # st.stop()
        
        st.header("Yield Prediction Model (LOYO Ridge)")
        st.write("Predictions are made using leave-one-year-out cross-validation.")

        # Prepare data
        df = merged_avg.drop(columns="geometry").copy()

        # LOYO Regression
        from sklearn.linear_model import Ridge
        from sklearn.metrics import mean_squared_error, mean_absolute_error
        import numpy as np
        from sklearn.linear_model import Ridge, Lasso, ElasticNet
        from sklearn.metrics import mean_squared_error, mean_absolute_error
        
        predictions = []
        metrics = []

        years_unique = sorted(df["year"].unique())

        for yr in years_unique:
            train = df[df["year"] != yr]
            test = df[df["year"] == yr]

            X_train = train[model_features].values
            y_train = train["yield"].values
            X_test = test[model_features].values
            y_test = test["yield"].values

            model = make_model_pipeline(model_choice, alpha, l1_ratio)

            # Train + predict
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)


            # Store predictions
            temp = test[["id2", "year"]].copy()
            temp["predicted_yield"] = y_pred
            predictions.append(temp)

            # Metrics
            mse = mean_squared_error(y_test, y_pred)
            rmse = np.sqrt(mse)
            mae = mean_absolute_error(y_test, y_pred)
            metrics.append({"year": yr, "rmse": rmse, "mae": mae})

        predictions_df = pd.concat(predictions)
        metrics_df = pd.DataFrame(metrics)

        st.subheader("Model Performance (LOYO)")
        st.dataframe(metrics_df)

        # Final model fit on all data for scenario prediction
        final_model = make_model_pipeline(model_choice, alpha, l1_ratio)
        final_model.fit(df[model_features], df["yield"].astype(float))

        st.divider()
        st.subheader("Predict Your Scenario")
        
        ranges = df[model_features].agg(["min", "median", "max"]).T
        
        with st.form("scenario_form"):
            st.write("Enter values for the selected features. The model will predict yield (bu/acre).")
        
            user_vals = {}
            for feat in model_features:
                default_val = float(ranges.loc[feat, "median"])
                user_vals[feat] = st.number_input(
                    label=f"{feat} ({FEATURE_UNITS.get(feat,'')})",
                    value=default_val,
                    step=0.1,
                    format="%.4f",
                )
        
            submitted = st.form_submit_button("Predict yield")
        
        if submitted:
            user_X = pd.DataFrame([user_vals], columns=model_features)
            pred = float(final_model.predict(user_X)[0])
            st.success(f"Predicted yield: **{pred:.2f} bu/acre**")
        
            flags = []
            for feat in model_features:
                v = user_vals[feat]
                mn = float(ranges.loc[feat, "min"])
                mx = float(ranges.loc[feat, "max"])
                if v < mn or v > mx:
                    flags.append(f"- `{feat}` is outside the training range [{mn:.4f}, {mx:.4f}]")
        
            if flags:
                st.warning(
                    "Some inputs are outside the data range the model learned from, so this prediction may be less reliable:\n"
                    + "\n".join(flags)
                )

        st.divider()
        st.subheader("Feature Effect (1D ALE)")
        
        ale_feature = st.selectbox(
            "Select a feature to view its effect on predicted yield",
            model_features,
            index=0
        )
        
        n_bins = st.slider("ALE bins", min_value=5, max_value=50, value=20, step=1)
        
        ale_df = ale_1d(final_model, df[model_features], ale_feature, n_bins=n_bins)
        
        if ale_df.empty:
            st.info("Not enough variation in this feature to compute ALE.")
        else:
            st.caption("ALE is centered at 0. Positive values mean higher predicted yield relative to average.")
        
            # Streamlit line chart wants index; keep it simple
            plot_df = ale_df.set_index("x")[["ale"]]
            st.line_chart(plot_df)
        
            st.write(
                f"Interpretation: moving **{ale_feature}** to the right changes predicted yield by the amount shown "
                f"(holding other features at their observed values within each bin)."
            )


        
    # Tab 3: Data Dictionary
    with tab3:
        st.header("Data Dictionary")
    
        st.markdown("""
        ### Climate & Environmental Variables
    
        **sph — Near-Surface Specific Humidity (g/kg)**  
        Amount of water vapor contained in the air.
    
        **vpd — Mean Vapor Pressure Deficit (kPa)**  
        Measures the "drying power" of air — higher VPD = more evaporative demand.
    
        **pr — Precipitation (kg/m²)**  
        Total precipitation amount.
    
        **rmin — Minimum Near-Surface Relative Humidity (%)**  
        The minimum daily percent of water vapor in the air relative to how much could be held at that temperature.
    
        **rmax — Maximum Near-Surface Relative Humidity (%)**  
        The maximum daily percent of water vapor in the air relative to capacity.
    
        **srad — Surface Downwelling Solar Radiation (W/m²)**  
        How much sunlight reaches the ground.
    
        **tmmn — Minimum Near-Surface Air Temperature (°C)**  
        Daily minimum temperature.
    
        **tmmx — Maximum Near-Surface Air Temperature (°C)**  
        Daily maximum temperature.
    
        **vs — Wind Speed at 10 m (m/s)**  
        Average wind speed measured 10 meters above ground.
    
        **th — Wind Direction at 10 m (degrees)**  
        Direction from which the wind blows.
        """)
    
        st.info("These definitions follow standard climatology and meteorology conventions commonly used in agricultural modeling.")



# Run App
if __name__ == "__main__":
    main()
